language: node_js

node_js:
  - "8"

install:
  - npm install

script:
  - npm run verify
  - npm run eslint

deploy:
  provider: npm
  email: "koenkanters94@gmail.com"
  api_key:
    secure: PnLrOI+D0WWFRaPXjCSQ/0QrQoCUlzA5ipIoArdEPtXgGiyzFwAUpW5hnWF7ITnsEatYtJVBd59rm9PLspZzlXXTiVk0DVN+pB310Wr30+71BoHfEZipl5Z5RkhhbruaRCU65FgRaJpkwx97pvOEt3H/e3CwmTdw2JA6N0m0m19KLdeaNwRycVxbLow4z2a9pYc2p/YuGHkUwMOtGjd4zWFneRZyY1NzYaH90DQq69Jh7kyJPDSNfeD+gJbDShWo+ph/F6bsnToXLWL+C5qrhOEqLQHoiTThl7wa6y8VmXfL6OKOt4k31G+fUIK/UiJGFoaxrEZmk72VR0oVfo7ue0z0wnu+B8V2X1oM1JDC47hKcIOqMf8IqEXkM54A9cvM3LV25pHr5Z4zN0D51v7udUnZafhwCSJkbFWdbL9A2bReu+2OrLX98GAlwztJcvh0dDPXED1Re83lzOTqODtsrp39gBJb7/JB2Nka9Ye5vBucgonYpbWLh0IMHzQIvue5k8cMlKyNW48zM4ihXWNGX7A/VfQUfJWnmg+bNHk2JPKlqnEKYucfhKKYV+g/FAlqnVBmRpc5ncbnQCFE7w4DuY0h2nQZDyhaXJIvzRHdXyXeCoU8ZXBHuYDcXLCLw+RoqffeDxvg8tN5yWW+JEWuepySnx556vtrQkl9IuwO17g=
  on:
    tags: true
    branch: master
