language: node_js

node_js:
  - '8'

install:
  - npm install

script:
  - npm test
  - npm run verify
  - npm run eslint

deploy:
  provider: npm
  email: koenkanters94@gmail.com
  api_key:
    secure: ZXg4VSeWGUtqjXJ8zOSUmf+ETyV12QTXY4FUEMxHVT9V70WMXCcKX4LhfrYHSMy7LkPnG5E2b1GGj36CdqjbNwBCThr1luzS0VXA1wzvr3qzCTgaRpMQWSWNl67ygSUJrZ2q4jJj0UhkpVMluXPepXARTfO3UjS9ILch4U3T0iJ4WHjZMbXJl0LXBYEgdvjLXnQ91nekwTr7HGdTWNvA6u3r+uibZS7Yxu6HFJaJJWqdqtchXUbHrDrXdB6tIWDCYOIYFS0/dzYRikZlE8tZLcLeZKtIMxnc5Y44ncxmvjd58a57/atN+TNfV39vfS4IXkobFhR/KAnTUELgkrqmx8Md0k7d0WbqRmuDqzkY5b9toP6fCfW1UFSPuAygDBJeuWV33GT79IuAHczuMP17siYOVEBXTydu2K2yQEabucQxMIRqh1sEQCq8h0JwX2GtKGytK8lTnmh+b7Jh5u6huIlw2JjTjwAXgKaDyJzwyIQmlxOmwvyM9cNuiQFBWqdHe+0KK9dMv6h5jL/G/gpesNEPJeNUlXre2XktYVyVyiaqoxEYiDUzPTlzOhYbcTGDeLLglVYTV/BUILGDgRHX/Ug8JRk/LLOXtfAGM+r8O+MFguuqHcWOmoYi19ctt8yLHicJB3TVIUOydMRDSLsGQ7/krhzUssZ6Hd8zW6l7RAk=
  on:
    tags: true
    branch: master
