blank_issues_enabled: true
contact_links:
  - name: Zigbee2MQTT issue tracker
    url: https://github.com/Koenkk/zigbee2mqtt/issues/new/choose
    about: Preferably create an issue in the Zigbee2MQTT issue tracker. Only click on "Open a blank issue" below if you are conviced it really belongs in this issue tracker. 
