name: Auto format/lint

on: [pull_request_target]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-format-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check --fix
        run: pnpm run check --fix
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fix(ignore): auto format/lint"
          commit_options: --no-verify
